// Copyright (c) 2026 Theodoros Bebekis
// Licensed under the MIT License.

namespace PackForge;

/// <summary>
/// Generates Inno Setup scripts.
/// </summary>
static public class InnoSetupScriptGenerator
{
    // ● private
    static string R(PublisherProjectSettings Project, string Text) => PublisherProjectPatterns.Resolve(Text, Project);
    static string I(string Text) => (Text ?? string.Empty).Replace("\"", "\"\"");
    static string ToInnoPath(string PathText, string BaseFolder)
    {
        string Result = PathText ?? string.Empty;
        if (!string.IsNullOrWhiteSpace(Result) && !string.IsNullOrWhiteSpace(BaseFolder))
        {
            try
            {
                string FullPath = Path.GetFullPath(Result);
                string FullBase = Path.GetFullPath(BaseFolder);
                if (FullPath.StartsWith(FullBase, StringComparison.OrdinalIgnoreCase))
                    Result = Path.GetRelativePath(FullBase, FullPath);
            }
            catch
            {
            }
        }
        return Result.Replace('/', '\\');
    }
    static void AddSetupLine(StringBuilder Builder, string Key, string Value)
    {
        if (!string.IsNullOrWhiteSpace(Value))
            Builder.AppendLine(Key + "=" + Value);
    }
    static void EnsureFolderCanBeCreated(string FolderPath, string FieldTitle)
    {
        if (string.IsNullOrWhiteSpace(FolderPath))
            throw new Exception(FieldTitle + " is required.");
        if (File.Exists(FolderPath))
            throw new Exception(FieldTitle + " points to an existing file, not a folder." + Environment.NewLine + FolderPath);
        Directory.CreateDirectory(FolderPath);
    }

    // ● public
    /// <summary>
    /// Generates the Inno Setup script and returns its file path.
    /// </summary>
    static public string Generate(PublisherProjectSettings Project)
    {
        if (Project == null)
            throw new Exception("Project settings are null.");
        if (!Project.Inno.IsEnabled)
            throw new Exception("Inno Setup generation is disabled.");

        string PublishRootFolder = R(Project, Project.PublishRootFolder);
        if (string.IsNullOrWhiteSpace(PublishRootFolder))
            throw new Exception("Publish root folder is required.");

        EnsureFolderCanBeCreated(PublishRootFolder, "Publish root folder");

        string ScriptFileName = R(Project, Project.Inno.ScriptFileName);
        if (string.IsNullOrWhiteSpace(ScriptFileName))
            throw new Exception("Inno Setup script file name is required.");

        string ScriptFilePath = Path.Combine(PublishRootFolder, ScriptFileName);
        string SourceFolder = R(Project, Project.Inno.WindowsPublishFolderName);
        string OutputFolder = R(Project, Project.InstallerOutputFolderOrFallback);
        if (string.IsNullOrWhiteSpace(OutputFolder) || OutputFolder.IsSameText(PublishRootFolder))
            OutputFolder = ".";

        StringBuilder Builder = new();
        Builder.AppendLine("; " + R(Project, Project.AppName) + " Windows installer");
        Builder.AppendLine("; Generated by PackForge. Compile with Inno Setup on Windows.");
        Builder.AppendLine();
        Builder.AppendLine("#define MyAppName \"" + I(R(Project, Project.AppName)) + "\"");
        Builder.AppendLine("#define MyAppVersion \"" + I(R(Project, Project.Version)) + "\"");
        Builder.AppendLine("#define MyAppPublisher \"" + I(R(Project, Project.Inno.AppPublisher)) + "\"");
        Builder.AppendLine("#define MyAppExeName \"" + I(R(Project, Project.Inno.AppExeName)) + "\"");
        Builder.AppendLine("#define MyAppSourceDir \"" + I(ToInnoPath(SourceFolder, PublishRootFolder)) + "\"");
        Builder.AppendLine("#define MyAppOutputDir \"" + I(ToInnoPath(OutputFolder, PublishRootFolder)) + "\"");
        Builder.AppendLine("#define MyAppUrl \"" + I(R(Project, Project.Inno.AppPublisherUrl)) + "\"");
        Builder.AppendLine();
        Builder.AppendLine("[Setup]");
        Builder.AppendLine("; Never change AppId after the first public release.");
        Builder.AppendLine("AppId={{" + R(Project, Project.AppId).Trim('{', '}') + "}");
        Builder.AppendLine("AppName={#MyAppName}");
        Builder.AppendLine("AppVersion={#MyAppVersion}");
        Builder.AppendLine("AppVerName={#MyAppName} {#MyAppVersion}");
        Builder.AppendLine("AppPublisher={#MyAppPublisher}");
        Builder.AppendLine("AppPublisherURL={#MyAppUrl}");
        Builder.AppendLine("AppSupportURL=" + I(R(Project, string.IsNullOrWhiteSpace(Project.Inno.AppSupportUrl) ? Project.Inno.AppPublisherUrl : Project.Inno.AppSupportUrl)));
        Builder.AppendLine("AppUpdatesURL=" + I(R(Project, string.IsNullOrWhiteSpace(Project.Inno.AppUpdatesUrl) ? Project.Inno.AppPublisherUrl : Project.Inno.AppUpdatesUrl)));
        Builder.AppendLine();
        Builder.AppendLine("DefaultDirName=" + R(Project, Project.Inno.DefaultDirName));
        Builder.AppendLine("DefaultGroupName=" + R(Project, Project.Inno.DefaultGroupName));
        Builder.AppendLine("DisableProgramGroupPage=yes");
        Builder.AppendLine("PrivilegesRequired=" + R(Project, Project.Inno.PrivilegesRequired));
        Builder.AppendLine();
        AddSetupLine(Builder, "ArchitecturesAllowed", R(Project, Project.Inno.ArchitecturesAllowed));
        AddSetupLine(Builder, "ArchitecturesInstallIn64BitMode", R(Project, Project.Inno.ArchitecturesInstallIn64BitMode));
        Builder.AppendLine("MinVersion=10.0");
        Builder.AppendLine();
        Builder.AppendLine("OutputDir={#MyAppOutputDir}");
        Builder.AppendLine("OutputBaseFilename=" + R(Project, Project.Inno.OutputBaseFilename));
        Builder.AppendLine("Compression=" + R(Project, Project.Inno.Compression));
        Builder.AppendLine("SolidCompression=" + (Project.Inno.SolidCompression ? "yes" : "no"));
        Builder.AppendLine();
        Builder.AppendLine("UninstallDisplayName={#MyAppName}");
        Builder.AppendLine("UninstallDisplayIcon={app}\\{#MyAppExeName}");
        Builder.AppendLine("CloseApplications=yes");
        Builder.AppendLine("RestartApplications=no");
        Builder.AppendLine();
        Builder.AppendLine("WizardStyle=modern");
        Builder.AppendLine("DisableWelcomePage=no");
        Builder.AppendLine("DisableFinishedPage=no");
        AddSetupLine(Builder, "WizardImageFile", I(ToInnoPath(R(Project, Project.Inno.WizardImageFile), PublishRootFolder)));
        AddSetupLine(Builder, "WizardSmallImageFile", I(ToInnoPath(R(Project, Project.Inno.WizardSmallImageFile), PublishRootFolder)));
        AddSetupLine(Builder, "SetupIconFile", I(ToInnoPath(R(Project, string.IsNullOrWhiteSpace(Project.Inno.SetupIconFile) ? Project.WindowsIconFilePath : Project.Inno.SetupIconFile), PublishRootFolder)));
        Builder.AppendLine();
        Builder.AppendLine("; Enable these after obtaining a code-signing certificate.");
        Builder.AppendLine("; SignTool=signtool");
        Builder.AppendLine("; SignedUninstaller=yes");
        Builder.AppendLine();
        Builder.AppendLine("[Languages]");
        Builder.AppendLine("Name: \"english\"; MessagesFile: \"compiler:Default.isl\"");
        Builder.AppendLine();
        Builder.AppendLine("[Tasks]");
        Builder.AppendLine("Name: \"desktopicon\"; Description: \"{cm:CreateDesktopIcon}\"; GroupDescription: \"{cm:AdditionalIcons}\"; Flags: unchecked");
        Builder.AppendLine();
        Builder.AppendLine("[Files]");
        Builder.AppendLine("Source: \"{#MyAppSourceDir}\\*\"; DestDir: \"{app}\"; Flags: ignoreversion recursesubdirs createallsubdirs; Excludes: \"*.pdb\"");
        Builder.AppendLine();
        Builder.AppendLine("[Icons]");
        Builder.AppendLine("Name: \"{group}\\{#MyAppName}\"; Filename: \"{app}\\{#MyAppExeName}\"; WorkingDir: \"{app}\"");
        Builder.AppendLine("Name: \"{autodesktop}\\{#MyAppName}\"; Filename: \"{app}\\{#MyAppExeName}\"; WorkingDir: \"{app}\"; Tasks: desktopicon");
        Builder.AppendLine();
        Builder.AppendLine("[Run]");
        Builder.AppendLine("Filename: \"{app}\\{#MyAppExeName}\"; Description: \"{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}\"; WorkingDir: \"{app}\"; Flags: nowait postinstall skipifsilent");

        File.WriteAllText(ScriptFilePath, Builder.ToString(), new UTF8Encoding(false));
        return ScriptFilePath;
    }
}
